set dotenv-load := true

build-macos:
	cargo build --release --target x86_64-unknown-linux-musl

build-linux:
	cargo build --release

package:
	zip -j function.zip ./target/x86_64-unknown-linux-musl/release/bootstrap

# TODO: Make me more dynamic, based on the host OS?
publish: build-macos package
	aws create-function --role whos-home-lambda --function-name arrivals-handler --runtime provided.al2 --package-type Zip --zip-file function.zip
